###
GET http://localhost:8080/api/v1/users/1/personalTasks

###
POST http://localhost:8080/api/v1/users/1/personalTasks
Content-Type: application/json

{
  "title": "Test"
}

###
PATCH http://localhost:8080/api/v1/users/1/personalTasks
Content-Type: application/json

{
  "id": 1,
  "title": "Java is god"
}

###
DELETE http://localhost:8080/api/v1/users/1/personalTasks/3

###
GET http://localhost:8080/api/v1/users/1/projects

###
GET http://localhost:8080/api/v1/users/2/projects

###
GET http://localhost:8080/api/v1/projects/2/members

###
POST http://localhost:8080/api/v1/users/1/projects
Content-Type: application/json

{
"title": "Test"
}

###
POST http://localhost:8080/api/v1/users/2/projects
Content-Type: application/json

{
  "title": "Test"
}

###
POST http://localhost:8080/api/v1/users/1/addMember/projects/3
Content-Type: application/json

{
  "id": 2
}

###
POST http://localhost:8080/api/v1/users/1/removeMember/projects/3
Content-Type: application/json

{
  "id": 2
}

###
PATCH http://localhost:8080/api/v1/users/1/projects
Content-Type: application/json

{
  "id": "1"
}

###
DELETE http://localhost:8080/api/v1/projects/2
