###
POST http://localhost:8080/api/v1/users/1/projects
Content-Type: application/json

{
"title": "Test",
"description": "Test is funny"
}

###
PATCH http://localhost:8080/api/v1/projects
Content-Type: application/json

{
  "id": "1",
  "title": "Testing",
  "description": "Test is funny"
}

###
DELETE http://localhost:8080/api/v1/projects/2


###
GET http://localhost:8080/api/v1/users/1/projects

###
GET http://localhost:8080/api/v1/users/2/projects

###
GET http://localhost:8080/api/v1/projects/2/members